const data = {
    dogs: [
      {
        id: 1,
        name: "Dobby",
        breed: "Golden Retriever",
        age: 3,
        special: "potty trained", 
        image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      },
      {
        id: 2,
        name: "Zion",
        breed: "German Shepard",
        age: 24,
        special: "potty trained", 
        image:'https://cdn.britannica.com/79/232779-050-6B0411D7/German-Shepherd-dog-Alsatian.jpg',
      },
      {
        id: 3,
        name: "Sage",
        breed: "Affenpinscher",
        age: 8,
        special: "potty trained", 
        image: 'https://img1.wsimg.com/isteam/ip/e15f9974-f18f-47e5-84f5-a4e618157c2b/Pheona%20p1.jpeg',
      },
      {
        id: 4,
        name: "Wren",
        breed: "American Eskimo Dog",
        age: 2,
        special: "potty trained",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/fe/American_Eskimo_Dog_1.jpg", 
      },
      {
        id: 5,
        name: "Rory",
        breed: "Mini Australian Shepherd",
        age: 4,
        special: "potty trained", 
        image: "https://www.marvelousdogs.com/wp-content/uploads/2020/12/Mini-Australian-Shepherd-puppy-lying-in-the-grass.jpg",
      },
      {
        id: 6,
        name: "Tuna",
        breed: "Chow Chow",
        age: 2,
        special: "potty trained",
        image: "http://cdn.akc.org/content/article-body-image/chow_chow_body_image_2.jpg", 
      },
      {
        id: 7,
        name: "Dumbledore",
        breed: "Rottweiler",
        age: 26,
        special: "potty trained", 
        image: "https://cdn.britannica.com/69/234469-050-B883797B/Rottweiler-dog.jpg",
      },
      {
        id: 8,
        name: "River",
        breed: "Border Collie",
        age: 21,
        special: "potty trained",
        image: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F47%2F2021%2F03%2F02%2Fborder-collie-green-field-268313239-2000.jpeg", 
      },
      {
        id: 9,
        name: "Bacon",
        breed: "Pomeranian",
        age: 12,
        special: "potty trained",
        image: "https://www.thefarmersdog.com/digest/wp-content/uploads/2022/02/Pomeranian.jpg", 
      },
      {
        id: 10,
        name: "Parker",
        breed: "Havanese",
        age: 4,
        special: "potty trained", 
        image: "https://betterpet.com/wp-content/uploads/2022/07/havanese.jpg",
      },
      {
        id: 11,
        name: "Sookie",
        breed: "Newfoundland",
        age: 16,
        special: "potty trained", 
        image: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F47%2F2021%2F06%2F02%2Fnewfoundland-black-standing-grass-249332530-2000.jpg",
      },
      {
        id: 12,
        name: "Mia",
        breed: "Goldendoodle",
        age: 18,
        special: "potty trained", 
        image: "https://www.purina.co.uk/sites/default/files/styles/ttt_image_510/public/2021-02/Goldendoodle-image-2.jpg?itok=4akDbiY7",
      },
    ],
  };

  export default data;